apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifyTest.sender.fullname" . }}
  labels:
    {{- include "notifyTest.sender.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sender.replicaCount }}
  selector:
    matchLabels:
      {{- include "notifyTest.sender.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notifyTest.sender.labels" . | nindent 8 }}
        {{- with .Values.sender.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.sender.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.sender.securityContext | nindent 12 }}
          image: "{{ .Values.sender.image.repository }}:{{ .Values.sender.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.sender.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "notifyTest.sender.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.sender.resources | nindent 12 }}
          {{- with .Values.sender.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.sender.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
