apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifyTest.sender.fullname" . }}
  labels:
    {{- include "notifyTest.sender.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sender.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notifyTest.sender.selectorLabels" . | nindent 4 }}
