[versions]
coroutines = "1.10.2"
detekt = "1.23.8"
dnsJava = "3.6.3"
gradleFilterVersions = "0.1.16"
gradleUpdateVersions = "1.0.1"
gradleVersions = "0.53.0"
# @keep jdk target
jdk = "21"
junit = "6.0.1"
kotest = "6.0.5"
kotlin = "2.2.21"
kotlinLogging = "3.0.5"
kotlinter = "5.2.0"
mockk = "1.14.6"

[libraries]
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsJava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinLogging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
detektPlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleUpdateVersionsPlugin = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradleUpdateVersions" }
gradleVersionsFilterPlugin = { id = "se.ascp.gradle.gradle-versions-filter", version.ref = "gradleFilterVersions" }
gradleVersionsPluign = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
kotlinPlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinterPlugin = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
